[package]
name = "t_add_dsc_verify_1300"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
partial_sha256 = { path = "../../../../partial_sha256" }
sig_check_rsa = { path = "../../../utils/sig-check/rsa" }
fragmented_sig_check_rsa = { path = "../../utils/sig-check/rsa" }
utils = { path = "../../../utils/utils" }
commitment = { path = "../../utils/commitment/common" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
