[package]
name = "t_attest"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
common = { path = "../../zkpassport_libs/commitment/common" }
compare_age_lib = { path = "../../zkpassport_libs/compare/age" }
data_check_expiry = { path = "../../zkpassport_libs/data-check/expiry" }
scoped_nullifier = { path = "../../zkpassport_libs/commitment/scoped-nullifier" }
utils = { path = "../../zkpassport_libs/utils" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
