[package]
name = "t_add_id_data_1300"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
sig_check_rsa = { path = "../../../utils/sig-check/rsa" }
utils = { path = "../../../utils/utils" }
data_check_tbs_pubkey = { path = "../../../utils/data-check/tbs-pubkey" }
commitment = { path = "../../utils/commitment/dsc-to-id" }
